# MobArena v0.95.5 - Config-file
# Read the Wiki for details on how to set up this file: http://goo.gl/F5TTc
# Note: You -must- use spaces instead of tabs!
global-settings:
    enabled: false
    allowed-commands: /list, /pl
    update-notification: true
classes:
    Knight:
        items: diamond_sword, potion:8197:3
        armor: 306,307,308,309
    Tank:
        items: iron_sword, potion:8229:2
        armor: 310,311,312,313
    Archer:
        items: wood_sword, bow, arrow:256, potion:8197:3, bone
        armor: 298,299,300,301
    Chemist:
        items: stone_sword, potion:16428:30, potion:16388:8, potion:16389:20, potion:8197:3, potion:8226:1
        armor: 314,315,316,317
    Oddjob:
        items: stone_sword, flint_and_steel, netherrack:2, tnt:4, potion:8197:3
        armor: 298,299,300,301
arenas:
    default:
        settings:
            world: world
            enabled: false
            protect: true
            entry-fee: ''
            clear-wave-before-next: false
            clear-boss-before-next: false
            lightning: true
            auto-equip-armor: true
            soft-restore: false
            soft-restore-drops: false
            require-empty-inv-join: false
            require-empty-inv-spec: false
            hellhounds: false
            pvp-enabled: false
            monster-infight: false
            allow-teleporting: false
            spectate-on-death: true
            auto-respawn: true
            share-items-in-arena: true
            min-players: 0
            max-players: 0
            max-join-distance: 0
            first-wave-delay: 5
            wave-interval: 15
            final-wave: 0
            monster-limit: 100
            monster-exp: false
            keep-exp: true
            food-regen: false
            lock-food-level: true
            spout-class-select: false
            player-time-in-arena: world
            auto-ignite-tnt: true
            auto-start-timer: 0
            clear-wave-before-boss: false
            use-class-chests: false
            display-waves-as-level: false
            auto-ready: false
            display-timer-as-level: false
            use-scoreboards: true
        waves:
            recurrent:
                def1:
                    type: default
                    priority: 1
                    frequency: 1
                    monsters:
                        zombies: 10
                        skeletons: 10
                        spiders: 10
                        creepers: 10
                        wolves: 10
                spec1:
                    type: special
                    priority: 2
                    frequency: 4
                    monsters:
                        powered-creepers: 10
                        zombie-pigmen: 10
                        angry-wolves: 10
                        blazes: 10
            single:
                swarm1:
                    type: swarm
                    wave: 6
                    monster: slime
                    amount: low
                boss1:
                    type: boss
                    wave: 10
                    monster: cave_spider
                    health: high
                    abilities: arrows, root-target, throw-nearby
        rewards:
            waves:
                every:
                    '3': feather, bone, stick
                    '5': dirt:4, gravel:4, stone:4
                    '10': iron_ingot:10, gold_ingot:8
                after:
                    '7': minecart, storage_minecart, powered_minecart
                    '13': iron_sword, iron_pickaxe, iron_spade
                    '16': diamond_sword
        class-limits:
            Archer: -1
            Oddjob: -1
            Chemist: -1
            Tank: -1
            Knight: -1
        coords:
            p1: -66,138,117,-141.44994,13.3500595
            p2: 4,191,184,50.09996,29.400078
            arena: -31,166,148,313.94992,58.949997
            lobby: -48,172,130,311.9999,39.449993
            spawnpoints:
                first: -51,163,148,-89.100914,31.649996
                second: -31,163,128,0.14912625,57.45
                third: -11,162,148,88.649124,71.40001
                fifth: -16,172,133,49.64904,32.249985
                sixth: -46,172,163,-132.90092,41.99998
                fourth: -31,163,168,177.74913,72.149994
            spectator: -12,172,166,124.949425,10.349969
    cii:
        settings:
            world: world
            enabled: false
            protect: true
            entry-fee: ''
            clear-wave-before-next: false
            clear-boss-before-next: false
            lightning: true
            auto-equip-armor: true
            soft-restore: false
            soft-restore-drops: false
            require-empty-inv-join: false
            require-empty-inv-spec: false
            hellhounds: false
            pvp-enabled: false
            monster-infight: false
            allow-teleporting: false
            spectate-on-death: true
            auto-respawn: true
            share-items-in-arena: true
            min-players: 0
            max-players: 0
            max-join-distance: 0
            first-wave-delay: 5
            wave-interval: 15
            final-wave: 0
            monster-limit: 100
            monster-exp: false
            keep-exp: true
            food-regen: false
            lock-food-level: true
            spout-class-select: false
            player-time-in-arena: world
            auto-ignite-tnt: false
            auto-start-timer: 0
            clear-wave-before-boss: false
            use-class-chests: false
            display-waves-as-level: false
            auto-ready: false
            display-timer-as-level: false
            use-scoreboards: true
        waves:
            recurrent:
                def1:
                    type: default
                    priority: 1
                    frequency: 1
                    monsters:
                        zombies: 10
                        skeletons: 10
                        spiders: 10
                        creepers: 10
                        wolves: 10
                spec1:
                    type: special
                    priority: 2
                    frequency: 4
                    monsters:
                        powered-creepers: 10
                        zombie-pigmen: 10
                        angry-wolves: 10
                        blazes: 10
            single:
                swarm1:
                    type: swarm
                    wave: 6
                    monster: slime
                    amount: low
                boss1:
                    type: boss
                    wave: 10
                    monster: cave_spider
                    health: high
                    abilities: arrows, root-target, throw-nearby
        rewards:
            waves:
                every:
                    '3': feather, bone, stick
                    '5': dirt:4, gravel:4, stone:4
                    '10': iron_ingot:10, gold_ingot:8
                after:
                    '7': minecart, storage_minecart, powered_minecart
                    '13': iron_sword, iron_pickaxe, iron_spade
                    '16': diamond_sword
        class-limits:
            Archer: -1
            Oddjob: -1
            Chemist: -1
            Tank: -1
            Knight: -1
        coords:
            p1: 1598,60,955,310.20483,15.449994
            p2: 1657,74,984,246.15515,89.7
            l1: 1579,50,1041,115.484436,60.599995
            l2: 1612,67,1083,276.73392,32.249992
            lobby: 1650,72,973,268.35547,17.549976
            spectator: 1655,72,964,94.35543,27.599972
            arena: 1640,63,967,92.855415,10.799972
            spawnpoints:
                first: 1609,66,969,272.10968,38.400448
                second: 1613,66,961,328.05988,38.850464
                third: 1617,66,982,188.10968,32.850464
